GET http://localhost:5000/api/courses

###
POST http://localhost:5000/api/courses
Content-Type: application/json

{
    "titre": "Css 3",
    "type":"Apprenant",
    "description" : "cours informaiques",
    "contenu":  "bla bla ",
    "date" : "28/07/2021"
}

###
DELETE http://localhost:5000/api/course/60fc093812ee4222cc018a90
Content-Type: application/json
###
GET  http://localhost:5000/api/course/60fb5760833574374438ead2
###
POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"hichem",
    "email":"hichem@gmail.com",
    "password":"12345678",
    "role":"Apprenant"
}
###
DELETE http://localhost:5000/api/courses/6103f198cc1f640a3c44d7f5
