GET http://localhost:5000/api/courses

###
POST http://localhost:5000/api/courses
Content-Type: application/json

{
    "titre": "Css 3",
    "type":"Apprenant",
    "description" : "cours informaiques",
    "contenu":  "bla bla ",
    "date" : "28/07/2021"
}

###
DELETE http://localhost:5000/api/course/60fc093812ee4222cc018a90
Content-Type: application/json
###
GET  http://localhost:5000/api/course/60fb5760833574374438ead2
###
POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"hichem ",
    "email":"hichem@gmail.com",
    "password":"12345678",
    "role":"Admin",
    "nom":"hichem",
    "prenom":"Moussa"
}
###
DELETE http://localhost:5000/api/courses/6103f198cc1f640a3c44d7f5
###
GET http://localhost:5000/api/courses
###
GET http://localhost:5000/api/users
###
PUT http://localhost:5000/api/users/6102e2fd873e3533c81a8d20 HTTP/1.1
content-type: application/json
{
    "etat":"Accepter"
}
###
PUT http://localhost:5000/api/users/6102e2fd873e3533c81a8d20 HTTP/1.1
content-type: application/json
{
    "titre":"Node js"
}
###
GET  http://localhost:5000/api/quiz
###
POST  http://localhost:5000/api/quiz
Content-Type: application/json

{
    "titre":"titre ",
    "description":"description",
    "niveau":"1",
    "questions":{
        "question":"ble ble",
        "choix1":"1",
        "choix2":"2",
        "choix3":"3",
        "choix4":"4",
        "reponse" : "3"
    }
    
}
###
GET  http://localhost:5000/api/quiz/61221fc043f8aa80142ad35a
###
DELETE  http://localhost:5000/api/quiz/61221f683442e64104788307
###
PUT  http://localhost:5000/api/quiz/61221fc043f8aa80142ad35a
Content-Type: application/json

{
    "titre":"titre33",
    "description":"description",
    "niveau":"1",
    "questions":{
        "question":"ble ble",
        "choix1":"1",
        "choix2":"2",
        "choix3":"3",
        "choix4":"4",
        "reponse" : "4"
    }
    
}
###
PUT  http://localhost:5000/api/courses/61073112096c9054f851c025
Content-Type: application/json

{
    "description":"vklkrvrvrvrssc"
}